version: '3'

volumes:
  dev_mysql_data: {}
  dev_mysql_data_backups: {}

services:
  flask: &flask
    build:
      context: .
      dockerfile: ./compose/dev/flask/Dockerfile
    image: gogotask_dev_flask
    expose:
      - 5000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: /start

  mysql:
    build:
      context: .
      dockerfile: ./compose/dev/mysql/Dockerfile
    image: gogotask_dev_mysql
    volumes:
      - dev_mysql_data:/var/lib/mysql:Z
      - dev_mysql_data_backups:/backups:z
      - ./compose/dev/mysql/mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always
    ports:
      - "0.0.0.0:3306:3306"

  nginx:
    build:
      context: .
      dockerfile: ./compose/dev/nginx/Dockerfile
    image: gogotask_dev_nginx
    depends_on:
      - flask
    volumes:
      - ./compose/dev/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "127.0.0.1:80:80"

