#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mysql_ready() {
python << END
import sys
import pymysql

try:
    pymysql.connect(
	    database="${MYSQL_DATABASE}",
	    user="${MYSQL_USER}",
		password="${MYSQL_PASSWORD}",
		host="${MYSQL_HOST}",
		port=${MYSQL_PORT},
	)
except pymysql.connect.Error as err:
    sys.exit(-1)
sys.exit(0)

END
}

until mysql_ready; do
  >&2 echo 'Waiting for MySQL to becom available...'
  sleep 1
done
>&2 echo 'MySQL is available'

exec "$@"

