"""add test

Revision ID: 108e139d5ee6
Revises: 92f32373e519
Create Date: 2021-08-29 15:24:27.979706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108e139d5ee6'
down_revision = '92f32373e519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###
